CapstoneBackend/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :horses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  post "/login", to: "sessions#create"
  get "/me", to: "users#show"
  delete "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
end

CapstoneBackend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

CapstoneBackend/app/models/horse.rb
class Horse < ApplicationRecord
end

CapstoneBackend/app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password

    validates :username, presence: true, uniqueness: true
end

CapstoneBackend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ActionController::Cookies
    skip_before_action :verify_authenticity_token
end

CapstoneBackend/app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: %i[ show edit update destroy ]

  # GET /horses or /horses.json
  def index
    @horses = Horse.all
    render json: @horses
  end

  # GET /horses/1 or /horses/1.json
  def show
  end

  # GET /horses/new
  def new
    @horse = Horse.new
  end

  # GET /horses/1/edit
  def edit
  end

  # POST /horses or /horses.json
  def create
    @horse = Horse.new(horse_params)

    respond_to do |format|
      if @horse.save
        format.html { redirect_to horse_url(@horse), notice: "Horse was successfully created." }
        format.json { render :show, status: :created, location: @horse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horses/1 or /horses/1.json
  def update
    respond_to do |format|
      if @horse.update(horse_params)
        format.html { redirect_to horse_url(@horse), notice: "Horse was successfully updated." }
        format.json { render :show, status: :ok, location: @horse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horses/1 or /horses/1.json
  def destroy
    @horse.destroy

    respond_to do |format|
      format.html { redirect_to horses_url, notice: "Horse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horse
      @horse = Horse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def horse_params
      params.require(:horse).permit(:name, :location, :price, :image, :broker)
    end
end

CapstoneBackend/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      render json: user
    else
      render json: { errors: ["Invalid username or password"] }, status: :unauthorized
    end
  end

  def destroy
    session.delete :user_id
    head :no_content
  end
end

CapstoneBackend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find_by(id: session[:user_id])
    if user
      render json: user
    else
      render json: { error: "Not authorized" }, status: :unauthorized
    end
  end
  # takes a plaintext password and stores a hashed version as a password_digest
  def password=(new_password)
    self.password_digest = dumb_hash(new_password)
  end

  # checks if the hashed plaintext password matches the password_digest
  def authenticate(password)
    return nil unless dumb_hash(password) == password_digest
    self
  end
  def create
    user = User.create(user_params)
    session[:user_id] = user.id
    render json: user, status: :created
  end
  private

  # the hashing method
  def dumb_hash(input)
    input.bytes.reduce(:+)
  end

  def user_params
    params.permit(:username, :password, :password_confirmation)
  end
end

CapstoneBackend/app/helpers/application_helper.rb
module ApplicationHelper
end

CapstoneBackend/app/helpers/horses_helper.rb
module HorsesHelper
end

CapstoneBackend/app/helpers/sessions_helper.rb
module SessionsHelper
end

CapstoneBackend/app/helpers/users_helper.rb
module UsersHelper
end

CapstoneBackend/app/views/horses/_form.html.erb
<%= form_with(model: horse) do |form| %>
  <% if horse.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
        <% horse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :loacation, style: "display: block" %>
    <%= form.text_field :loacation %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :broker, style: "display: block" %>
    <%= form.text_field :broker %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

CapstoneBackend/app/views/horses/_horse.html.erb
<div id="<%= dom_id horse %>">
  <p>
    <strong>Name:</strong>
    <%= horse.name %>
  </p>

  <p>
    <strong>Loacation:</strong>
    <%= horse.loacation %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= horse.price %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= horse.image %>
  </p>

  <p>
    <strong>Broker:</strong>
    <%= horse.broker %>
  </p>

</div>

CapstoneBackend/app/views/horses/edit.html.erb
<h1>Editing horse</h1>

<%= render "form", horse: @horse %>

<br>

<div>
  <%= link_to "Show this horse", @horse %> |
  <%= link_to "Back to horses", horses_path %>
</div>

CapstoneBackend/app/views/horses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Horses</h1>

<div id="horses">
  <% @horses.each do |horse| %>
    <%= render horse %>
    <p>
      <%= link_to "Show this horse", horse %>
    </p>
  <% end %>
</div>

<%= link_to "New horse", new_horse_path %>

CapstoneBackend/app/views/horses/new.html.erb
<h1>New horse</h1>

<%= render "form", horse: @horse %>

<br>

<div>
  <%= link_to "Back to horses", horses_path %>
</div>

CapstoneBackend/app/views/horses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @horse %>

<div>
  <%= link_to "Edit this horse", edit_horse_path(@horse) %> |
  <%= link_to "Back to horses", horses_path %>

  <%= button_to "Destroy this horse", @horse, method: :delete %>
</div>

CapstoneBackend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapstoneBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

CapstoneBackend/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

CapstoneBackend/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

CapstoneBackend/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

CapstoneBackend/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

CapstoneBackend/app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f|%>
<%= f.label :user%>
<%= f.text_field :user%>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit%>
<% end %>

CapstoneBackend/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>